language: python
python: 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py35
    - TOX_ENV=flake8
before_install:
    - sudo rm -f /etc/boto.cfg
install:
    - pip install tox
script:
    - tox -e $TOX_ENV

matrix:
  include:
    - python: 3.6
      env:
        - TOX_ENV=py36
    - python: 3.6
      env:
        - TOX_ENV=flake8
    - python: 3.7
      dist: xenial
      sudo: true
      env:
        - TOX_ENV=py37
